SELECT GEN3.ID
FROM ECOLI_DATA AS GEN1

INNER JOIN ECOLI_DATA AS GEN2
ON GEN1.ID = GEN2.PARENT_ID

INNER JOIN ECOLI_DATA AS GEN3
ON GEN2.ID = GEN3.PARENT_ID

WHERE GEN1.PARENT_ID IS NULL

ORDER BY GEN3.ID ASC;