WITH RECURSIVE GEN_TREE AS (
    -- 1단계: 1세대 찾기
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 2단계: 다음 세대 계속 찾기
    SELECT E.ID, E.PARENT_ID, G.GEN + 1
    FROM ECOLI_DATA E
    JOIN GEN_TREE AS G ON E.PARENT_ID = G.ID
)

SELECT 
    COUNT(*) AS COUNT,
    G.GEN AS GENERATION
FROM GEN_TREE G
LEFT JOIN ECOLI_DATA AS E ON G.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY G.GEN
ORDER BY G.GEN
