-- 코드를 입력하세요
WITH BASE AS (SELECT 
    CRC.HISTORY_ID, 
    CRCC.DAILY_FEE,
    CRCC.CAR_TYPE,
    (DATEDIFF(CRC.END_DATE, CRC.START_DATE) + 1) AS RENTAL_DAYS,
    CASE
        WHEN DATEDIFF(CRC.END_DATE, CRC.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(CRC.END_DATE, CRC.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(CRC.END_DATE, CRC.START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE '할인없음'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRC
JOIN CAR_RENTAL_COMPANY_CAR CRCC ON CRCC.CAR_ID = CRC.CAR_ID
WHERE CRCC.CAR_TYPE = '트럭'
)

SELECT B.HISTORY_ID,
        FLOOR(B.DAILY_FEE * B.RENTAL_DAYS * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100)  AS FEE
FROM BASE B
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON P.CAR_TYPE = B.CAR_TYPE
    AND P.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, B.HISTORY_ID DESC;
