WITH BASE AS (
    SELECT 
        H.HISTORY_ID, CAR_TYPE, DAILY_FEE, 
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DAYS,
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT B.HISTORY_ID, 
       FLOOR(DAILY_FEE * RENTAL_DAYS * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM BASE AS B
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
    ON P.CAR_TYPE = B.CAR_TYPE AND B.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, B.HISTORY_ID DESC;