SELECT FH.FLAVOR
FROM FIRST_HALF FH 
JOIN 
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
     FROM JULY
     GROUP BY FLAVOR) JULY 
     ON FH.FLAVOR = JULY.FLAVOR
ORDER BY (FH.TOTAL_ORDER  + JULY.JULY_TOTAL) DESC
LIMIT 3;