SELECT APNT_NO, PT_NAME, AP.PT_NO, AP.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AP
JOIN DOCTOR ON AP.MDDR_ID = DOCTOR.DR_ID 
JOIN PATIENT ON PATIENT.PT_NO = AP.PT_NO
WHERE 
    AP.MCDP_CD = 'CS' 
    AND 
    APNT_YMD LIKE '2022-04-13%' 
    AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;