WITH RECURSIVE TIMES AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM TIMES
    WHERE HOUR < 23
)


SELECT T.HOUR, 
        COUNT(A.ANIMAL_ID) AS COUNT
FROM TIMES T
LEFT JOIN ANIMAL_OUTS A ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR;