WITH RECURSIVE TIMES AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 FROM TIMES WHERE HOUR < 23    
)

SELECT T.HOUR, COUNT(ANIMAL.ANIMAL_ID) AS COUNT
FROM TIMES AS T
LEFT JOIN ANIMAL_OUTS AS ANIMAL
ON HOUR(ANIMAL.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR ASC;