SELECT USER_ID, NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UGB
JOIN USED_GOODS_USER UGU ON UGU.USER_ID = UGB.WRITER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;