SELECT E1.ID, 
       E1.GENOTYPE, 
       E2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS E1
INNER JOIN ECOLI_DATA AS E2
    ON E2.ID = E1.PARENT_ID
WHERE E2.GENOTYPE & E1.GENOTYPE = E2.GENOTYPE
ORDER BY E1.ID ASC;



