WITH MAX_PRICES AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT MP.CATEGORY, MP.MAX_PRICE, F.PRODUCT_NAME
FROM MAX_PRICES MP
JOIN FOOD_PRODUCT F ON F.CATEGORY = MP.CATEGORY AND F.PRICE = MP.MAX_PRICE
ORDER BY MAX_PRICE DESC; 
